# Stage 1: Build the backend
FROM node:latest AS backend-build
WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm install
COPY backend .
RUN npm run build
EXPOSE 3000

# Stage 2: Create a lightweight image
FROM node:alpine
WORKDIR /app/backend
COPY --from=backend-build /app/backend .
CMD ["npm", "start"]

